version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Winmusic@123   # ⚠️ ต้อง strong เท่านั้น
    ports:
      - "1433:1433"
    restart: always

  api:
    build: ./backend
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASS=Winmusic@123
      - DB_NAME=master
    depends_on:
      - db
    restart: always

  web:
    image: saksitku/winmusic:latest
    container_name: web
    ports:
      - "80:80"
    restart: always